using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AgainstTheStorm_Assistant_App.Daten.Buildings
{
    internal class Building
    {
        public enum Buildings
        {
            AdvancedRainCollector,
            Apothocary,
            Artisan,
            Bakery,
            BathHouse,
            Beanery,
            Brewery,
            BrickOven,
            Brickyard,
            Butcher,
            Carpenter,
            Cellar,
            ClanHall,
            ClayPit,
            Clothier,
            Cookhouse,
            Cooperage,
            CrudeWorkstation,
            Distillery,
            DruidsHut,
            ExplorersLodge,
            FieldKitchen,
            Finesmith,
            FlawlessBrewery,
            FlawlessRainMill,
            ForagersCamp,
            ForestersHut,
            Forum,
            Furnace,
            GeyserPump,
            Granary,
            Greenhouse,
            Grill,
            GuildHouse,
            HallowedHerbGarden,
            HallowedSmallFarm,
            HarvestersCamp,
            HerbalistsCamp,
            HerbGarden,
            HolyMarket,
            HolyTemple,
            Homestead,
            Kiln,
            Leatherworker,
            LumberMill,
            MakeshiftPost,
            Manufactury,
            Market,
            Mine,
            Monastery,
            Plantation,
            Press,
            Provisioner,
            RainCollector,
            RainMill,
            RainpunkFoundry,
            Ranch,
            Scribe,
            SmallFarm,
            SmallForagersCamp,
            SmallHerbalistsCamp,
            SmallTrappersCamp,
            Smelter,
            Smithy,
            Smokehouse,
            StampingMill,
            StonecuttersCamp,
            Supplier,
            Tavern,
            TeaDoctor,
            Teahouse,
            Temple,
            Tinctuary,
            Tinkerer,
            Toolshop,
            TrappersCamp,
            WoodcuttersCamp,
            Workshop,
            Weaver
        }
    }
}
